### PR TITLE
docs: update example to use the purplin theme

### LINKED ISSUE #10: Lovely theme! I think there's a small fix needed...?
Hi friend, lovely work on this theme!

I think there's a small issue with the [example.md](https://github.com/moudev/slidev-theme-purplin/blob/main/example.md) file. It currently sets `theme: none` but it should actually have `theme: purplin`, right?

Happy to send in a PR in case I didn't miss anything about that.

### PR DESCRIPTION
**Pull request by lirantal**
Fixes #10 to ensure the example reference file `example.md` is functional.

### CODE REVIEW

**Comment by moudev** [comment]
thanks, @lirantal. The build process has failed. I found the error is because of the theme's path, in the official themes they put `theme: ./`
- https://github.com/slidevjs/themes/blob/main/packages/theme-seriph/example.md

I tried to make the changes. I followed the [Checking out pull requests locally](https://docs.github.com/es/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally
) but it is necessary to create another pull request. Sorry, I don't have much experience in these cases.

can you please make the change? thanks for your help.

**Comment by lirantal** [comment]
Thank you for looking into that @moudev, I just now updated it with a comment too. Let's see if it deploys correctly

**Comment by moudev** [comment]
Everything is fine now, Lira. Thanks for your help!

**Comment by lirantal** [comment]
Thank *you* for pointing me to the right place :-)

**Pull request merged**
